#+TITLE: 2021 11 11
* 2021-11-11 retro

** linxuyalun
主题： IPC / Data Store & Data Search & CLP
- DDIA 很好，对于系统方向的工作来说，其收益不显著但稳定。
- 认为一直读论文也挺好的，可以以一个方向为导向，采取 survey 的方式，讲
  一些核心 idea （一个主题下的数个工作）。讲者由于系统性阅读，对该领域
  的认识可以做到非常深刻；听者会对这个领域的内容有一个整体的认知；实现
  双赢。
- 感觉准备的非常充分，单看材料也比较有条理且丰富，这就说明花时间准备是提
  高质量的关键。
- vanderchen 也认同这样系统地讲一个主题的工作是一个好的 idea。
** aak1247
主题： Big table & Spanner
- 讲的东西比较有连贯性，从之前的 TiDB 到 Big Table 还有 Spanner，在同一
  个大的研究方向之下上下文比较连贯，因此比较好讲，可以专注于该工作本身的
  内容；然而时间比较少，准备一次可能成本比较高，需要提前准备，这对人的要
  求其实是比较高的。
- 花费较大的时间成本，希望是能够对于日常的研究和工作内容有帮助；aak1247
  本身的工作性质导致他会在各个方面都有所涉猎，难以聚焦于某一个具体的细分
  方向，但在攻克难题的时候也希望能从一个方向出发寻找一些新的思路和启发；
  因此希望是基于个人当前研究和工作中遇到的难题，寻找一个方向去研究，可以
  不局限于论文，可以从软件工程的角度去分析研究。
- 一个 Enhancement：内容上如果可行的话可以注意一下顺序，从基础的工作讲起，
  否则可能会有额外的同步上下文的成本。
** c1
主题： Category Theory: Functor 的性质，Function Types 和 Monad
- 这个主题明显陷入了一个过于追求细节的问题，而且其中的知识太过于理论，总
  而言之收益不太明显；应该更加注意结合实际场景和例子去介绍相关的内容。
- 对于 c1 来说，这个主题的学习过程其实起到的是一个打破神话的作用，因为有
  关于程序语言，语言特性，类型系统以及各种程序设计语言中“炫技”的部分，这
  些内容我们经常会在各种个样的场合看到各种各样主观的论调，很多时候我们容
  易被这些言论带跑偏，而失去了自己思考并收获有趣问题的答案的机会和乐趣，
  例如 c1 自己曾经陷入到所谓函数式邪教之中，相当于拿着锤子到处找钉子，知
  其所以然有助于回归本源，从一个更加本质的角度看待我们日常遇到的问题。祛
  媚。
** VanderChen
主题：OpenStack - RPC & Common MQ Comparison / Orion
- 经过多个话题的尝试，似乎找到了方向：专注到系统这方便来，用云控制面构架
  开始，涉及到细化到里面的模块。未来从云的控制面，再到云边协同的控制面；
  形成一个体系化的知识网络。
- 从内容的选择方面，应当选择一族完整的概念，使得大家对整个系统有一个概观
  的了解。

** 改进点
大家在这个 season 的 salon 的实践中，形式和内容的选择上逐渐都或多或少地
收敛到 *选择一个方向，讲者做系统性的学习，并使得听者有一个概观的认知，从
而实现一定程度的双赢*，从而规避掉我们之前遇到的讲者自己学习，而听者完全
一脸懵逼的问题。
